image: microsoft/dotnet:1-sdk-projectjson

stages:
  - build
  - test

build:
  stage: build
  artifacts:
    untracked: true
  script:
  - dotnet restore src/Ferro/
  - dotnet restore test/Ferro.Tests/
  - dotnet build src/Ferro/
  - dotnet build test/Ferro.Tests/

test:
  stage: test
  script:
  - cd test/Ferro.Tests/ && dotnet test
