image: microsoft/dotnet:1-sdk-projectjson

build-and-test:
  script:
  - dotnet restore src/Ferro/
  - dotnet restore test/Ferro.Tests/
  - dotnet build src/Ferro/
  - dotnet build test/Ferro.Tests/
  - cd test/Ferro.Tests/ && dotnet test

pages:
  image: alpine:latest
  script:
  - cp -R ./docs/ ./public/
  artifacts:
    paths: [public]
  only: [master]
