#!/bin/bash -eu
cd "$(dirname "$(python -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' "${BASH_SOURCE[0]}")")";

docker stop -t 120 "$(docker ps -q --filter ancestor=registry.gitlab.com/ditto/ditto:docktorrent)";
